services:

  pay:
    container_name: php.pay
    build:
      context: .
      dockerfile: docker/config/php-fpm/Dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/var/www/html
    networks:
      pay:
        aliases:
          - php.pay

  nginx:
    container_name: nginx.pay
    build:
      context: .
      dockerfile: docker/config/nginx/Dockerfile
    volumes:
      - ./app:/var/www/html
    ports:
      - ${APP_OUTER_PORT}:80
    networks:
      pay:
        aliases:
          - nginx.pay

  db:
    image: ${DB_IMAGE}
    container_name: db.pay
    environment:
      TZ: ${TZ}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_OUTER_PORT}:${DB_PORT}
    volumes:
        - db:/var/lib/mysql
    networks:
        pay:
          aliases:
            - db.pay

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP порт
      - "15672:15672"   # Web UI порт
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      pay:
        aliases:
          - rabbitmq.pay

  messenger-worker:
    container_name: messenger.worker.pay
    build:
      context: .
      dockerfile: docker/config/php-fpm/Dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/var/www/html
    command: php bin/console messenger:consume async -vv --time-limit=3600 --memory-limit=128M
    depends_on:
      - rabbitmq
      - db
    restart: always
    networks:
      pay:
        aliases:
          - messenger.worker.pay

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/db/data
      o: bind
  rabbitmq_data:
    driver: local

networks:
  pay:
    name: pay